import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"], weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Khoa Tran - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased bg-[#0b0709]`}
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
